# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uavcontrol_msgs/BasicDataTypeAndValue.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BasicDataTypeAndValue(genpy.Message):
  _md5sum = "43928e1d51d365ceca1cc00365d754f1"
  _type = "uavcontrol_msgs/BasicDataTypeAndValue"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string name

uint8 type
uint8 INTEGER=1
uint8 BOOLEAN=2
uint8 FLOAT=3
uint8 DOUBLE=4
uint8 STRING=5

int32 integer_value
bool boolean_value
float32 float_value
float64 double_value
string string_value"""
  # Pseudo-constants
  INTEGER = 1
  BOOLEAN = 2
  FLOAT = 3
  DOUBLE = 4
  STRING = 5

  __slots__ = ['name','type','integer_value','boolean_value','float_value','double_value','string_value']
  _slot_types = ['string','uint8','int32','bool','float32','float64','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       name,type,integer_value,boolean_value,float_value,double_value,string_value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BasicDataTypeAndValue, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.name is None:
        self.name = ''
      if self.type is None:
        self.type = 0
      if self.integer_value is None:
        self.integer_value = 0
      if self.boolean_value is None:
        self.boolean_value = False
      if self.float_value is None:
        self.float_value = 0.
      if self.double_value is None:
        self.double_value = 0.
      if self.string_value is None:
        self.string_value = ''
    else:
      self.name = ''
      self.type = 0
      self.integer_value = 0
      self.boolean_value = False
      self.float_value = 0.
      self.double_value = 0.
      self.string_value = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BiBfd().pack(_x.type, _x.integer_value, _x.boolean_value, _x.float_value, _x.double_value))
      _x = self.string_value
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.type, _x.integer_value, _x.boolean_value, _x.float_value, _x.double_value,) = _get_struct_BiBfd().unpack(str[start:end])
      self.boolean_value = bool(self.boolean_value)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.string_value = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.string_value = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_BiBfd().pack(_x.type, _x.integer_value, _x.boolean_value, _x.float_value, _x.double_value))
      _x = self.string_value
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.name = str[start:end]
      _x = self
      start = end
      end += 18
      (_x.type, _x.integer_value, _x.boolean_value, _x.float_value, _x.double_value,) = _get_struct_BiBfd().unpack(str[start:end])
      self.boolean_value = bool(self.boolean_value)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.string_value = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.string_value = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_BiBfd = None
def _get_struct_BiBfd():
    global _struct_BiBfd
    if _struct_BiBfd is None:
        _struct_BiBfd = struct.Struct("<BiBfd")
    return _struct_BiBfd
