# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uavcontrol_msgs/WindowPosition.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class WindowPosition(genpy.Message):
  _md5sum = "89d76cf2a4942da77237e3ebfe45c4de"
  _type = "uavcontrol_msgs/WindowPosition"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

#模式：0：空闲  1.kcf   3.deepsort/sort(点击的id) 
uint8 mode


#波门位置X,#波门位置Y(kcf,点击画面的功能的时候使用),左上角为（0,0）
int16 origin_x
int16 origin_y
int16 width
int16 height 

#波门位置X,#波门位置Y
#int16 window_position_x = origin_x + width/2
#int16 window_position_y = origin_y + height/2
int16 window_position_x
int16 window_position_y

#算法检测结果的ID
int32 track_id

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','mode','origin_x','origin_y','width','height','window_position_x','window_position_y','track_id']
  _slot_types = ['std_msgs/Header','uint8','int16','int16','int16','int16','int16','int16','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,mode,origin_x,origin_y,width,height,window_position_x,window_position_y,track_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(WindowPosition, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.mode is None:
        self.mode = 0
      if self.origin_x is None:
        self.origin_x = 0
      if self.origin_y is None:
        self.origin_y = 0
      if self.width is None:
        self.width = 0
      if self.height is None:
        self.height = 0
      if self.window_position_x is None:
        self.window_position_x = 0
      if self.window_position_y is None:
        self.window_position_y = 0
      if self.track_id is None:
        self.track_id = 0
    else:
      self.header = std_msgs.msg.Header()
      self.mode = 0
      self.origin_x = 0
      self.origin_y = 0
      self.width = 0
      self.height = 0
      self.window_position_x = 0
      self.window_position_y = 0
      self.track_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B6hi().pack(_x.mode, _x.origin_x, _x.origin_y, _x.width, _x.height, _x.window_position_x, _x.window_position_y, _x.track_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.mode, _x.origin_x, _x.origin_y, _x.width, _x.height, _x.window_position_x, _x.window_position_y, _x.track_id,) = _get_struct_B6hi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B6hi().pack(_x.mode, _x.origin_x, _x.origin_y, _x.width, _x.height, _x.window_position_x, _x.window_position_y, _x.track_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 17
      (_x.mode, _x.origin_x, _x.origin_y, _x.width, _x.height, _x.window_position_x, _x.window_position_y, _x.track_id,) = _get_struct_B6hi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B6hi = None
def _get_struct_B6hi():
    global _struct_B6hi
    if _struct_B6hi is None:
        _struct_B6hi = struct.Struct("<B6hi")
    return _struct_B6hi
