// Generated by gencpp from file uavcontrol_msgs/arucoTrigger.msg
// DO NOT EDIT!


#ifndef UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGER_H
#define UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGER_H

#include <ros/service_traits.h>


#include <uavcontrol_msgs/arucoTriggerRequest.h>
#include <uavcontrol_msgs/arucoTriggerResponse.h>


namespace uavcontrol_msgs
{

struct arucoTrigger
{

typedef arucoTriggerRequest Request;
typedef arucoTriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct arucoTrigger
} // namespace uavcontrol_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uavcontrol_msgs::arucoTrigger > {
  static const char* value()
  {
    return "9a74408ed4558f2d49b9e90001338a55";
  }

  static const char* value(const ::uavcontrol_msgs::arucoTrigger&) { return value(); }
};

template<>
struct DataType< ::uavcontrol_msgs::arucoTrigger > {
  static const char* value()
  {
    return "uavcontrol_msgs/arucoTrigger";
  }

  static const char* value(const ::uavcontrol_msgs::arucoTrigger&) { return value(); }
};


// service_traits::MD5Sum< ::uavcontrol_msgs::arucoTriggerRequest> should match
// service_traits::MD5Sum< ::uavcontrol_msgs::arucoTrigger >
template<>
struct MD5Sum< ::uavcontrol_msgs::arucoTriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uavcontrol_msgs::arucoTrigger >::value();
  }
  static const char* value(const ::uavcontrol_msgs::arucoTriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uavcontrol_msgs::arucoTriggerRequest> should match
// service_traits::DataType< ::uavcontrol_msgs::arucoTrigger >
template<>
struct DataType< ::uavcontrol_msgs::arucoTriggerRequest>
{
  static const char* value()
  {
    return DataType< ::uavcontrol_msgs::arucoTrigger >::value();
  }
  static const char* value(const ::uavcontrol_msgs::arucoTriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uavcontrol_msgs::arucoTriggerResponse> should match
// service_traits::MD5Sum< ::uavcontrol_msgs::arucoTrigger >
template<>
struct MD5Sum< ::uavcontrol_msgs::arucoTriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uavcontrol_msgs::arucoTrigger >::value();
  }
  static const char* value(const ::uavcontrol_msgs::arucoTriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uavcontrol_msgs::arucoTriggerResponse> should match
// service_traits::DataType< ::uavcontrol_msgs::arucoTrigger >
template<>
struct DataType< ::uavcontrol_msgs::arucoTriggerResponse>
{
  static const char* value()
  {
    return DataType< ::uavcontrol_msgs::arucoTrigger >::value();
  }
  static const char* value(const ::uavcontrol_msgs::arucoTriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGER_H
