// Generated by gencpp from file uavcontrol_msgs/ArucoInfo.msg
// DO NOT EDIT!


#ifndef UAVCONTROL_MSGS_MESSAGE_ARUCOINFO_H
#define UAVCONTROL_MSGS_MESSAGE_ARUCOINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace uavcontrol_msgs
{
template <class ContainerAllocator>
struct ArucoInfo_
{
  typedef ArucoInfo_<ContainerAllocator> Type;

  ArucoInfo_()
    : header()
    , aruco_num(0)
    , detected(false)
    , position()
    , orientation()
    , sight_angle()  {
      position.assign(0.0);

      orientation.assign(0.0);

      sight_angle.assign(0.0);
  }
  ArucoInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , aruco_num(0)
    , detected(false)
    , position()
    , orientation()
    , sight_angle()  {
  (void)_alloc;
      position.assign(0.0);

      orientation.assign(0.0);

      sight_angle.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _aruco_num_type;
  _aruco_num_type aruco_num;

   typedef uint8_t _detected_type;
  _detected_type detected;

   typedef boost::array<float, 3>  _position_type;
  _position_type position;

   typedef boost::array<float, 4>  _orientation_type;
  _orientation_type orientation;

   typedef boost::array<float, 2>  _sight_angle_type;
  _sight_angle_type sight_angle;





  typedef boost::shared_ptr< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> const> ConstPtr;

}; // struct ArucoInfo_

typedef ::uavcontrol_msgs::ArucoInfo_<std::allocator<void> > ArucoInfo;

typedef boost::shared_ptr< ::uavcontrol_msgs::ArucoInfo > ArucoInfoPtr;
typedef boost::shared_ptr< ::uavcontrol_msgs::ArucoInfo const> ArucoInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.aruco_num == rhs.aruco_num &&
    lhs.detected == rhs.detected &&
    lhs.position == rhs.position &&
    lhs.orientation == rhs.orientation &&
    lhs.sight_angle == rhs.sight_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uavcontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4317d8c5571fc3b7219e3fa681ec1bab";
  }

  static const char* value(const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4317d8c5571fc3b7ULL;
  static const uint64_t static_value2 = 0x219e3fa681ec1babULL;
};

template<class ContainerAllocator>
struct DataType< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uavcontrol_msgs/ArucoInfo";
  }

  static const char* value(const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"## aruco编码\n"
"int32 aruco_num\n"
"\n"
"## 是否检测到目标\n"
"bool detected\n"
"\n"
"## 目标位置-相机坐标系-(x,y,z)\n"
"## 从相机往前看，物体在相机右方x为正，下方y为正，前方z为正\n"
"float32[3] position\n"
"\n"
"## 目标姿态-四元数-(qx,qy,qz,qw)\n"
"float32[4] orientation\n"
"\n"
"## 视线角度-相机系下-(右方x角度为正,下方y角度为正)\n"
"float32[2] sight_angle\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.aruco_num);
      stream.next(m.detected);
      stream.next(m.position);
      stream.next(m.orientation);
      stream.next(m.sight_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArucoInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uavcontrol_msgs::ArucoInfo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "aruco_num: ";
    Printer<int32_t>::stream(s, indent + "  ", v.aruco_num);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "position: ";
    if (v.position.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.position[i]);
    }
    if (v.position.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "orientation: ";
    if (v.orientation.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.orientation.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.orientation[i]);
    }
    if (v.orientation.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sight_angle: ";
    if (v.sight_angle.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.sight_angle.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.sight_angle[i]);
    }
    if (v.sight_angle.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAVCONTROL_MSGS_MESSAGE_ARUCOINFO_H
