// Generated by gencpp from file uavcontrol_msgs/arucoTriggerResponse.msg
// DO NOT EDIT!


#ifndef UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGERRESPONSE_H
#define UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uavcontrol_msgs
{
template <class ContainerAllocator>
struct arucoTriggerResponse_
{
  typedef arucoTriggerResponse_<ContainerAllocator> Type;

  arucoTriggerResponse_()
    : response(false)  {
    }
  arucoTriggerResponse_(const ContainerAllocator& _alloc)
    : response(false)  {
  (void)_alloc;
    }



   typedef uint8_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct arucoTriggerResponse_

typedef ::uavcontrol_msgs::arucoTriggerResponse_<std::allocator<void> > arucoTriggerResponse;

typedef boost::shared_ptr< ::uavcontrol_msgs::arucoTriggerResponse > arucoTriggerResponsePtr;
typedef boost::shared_ptr< ::uavcontrol_msgs::arucoTriggerResponse const> arucoTriggerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uavcontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "003b81baa95ab323fc1ddf3c7d0bee81";
  }

  static const char* value(const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x003b81baa95ab323ULL;
  static const uint64_t static_value2 = 0xfc1ddf3c7d0bee81ULL;
};

template<class ContainerAllocator>
struct DataType< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uavcontrol_msgs/arucoTriggerResponse";
  }

  static const char* value(const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool response\n"
"\n"
;
  }

  static const char* value(const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arucoTriggerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uavcontrol_msgs::arucoTriggerResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "response: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGERRESPONSE_H
