// Generated by gencpp from file uavcontrol_msgs/arucoTriggerRequest.msg
// DO NOT EDIT!


#ifndef UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGERREQUEST_H
#define UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uavcontrol_msgs
{
template <class ContainerAllocator>
struct arucoTriggerRequest_
{
  typedef arucoTriggerRequest_<ContainerAllocator> Type;

  arucoTriggerRequest_()
    : request(false)  {
    }
  arucoTriggerRequest_(const ContainerAllocator& _alloc)
    : request(false)  {
  (void)_alloc;
    }



   typedef uint8_t _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct arucoTriggerRequest_

typedef ::uavcontrol_msgs::arucoTriggerRequest_<std::allocator<void> > arucoTriggerRequest;

typedef boost::shared_ptr< ::uavcontrol_msgs::arucoTriggerRequest > arucoTriggerRequestPtr;
typedef boost::shared_ptr< ::uavcontrol_msgs::arucoTriggerRequest const> arucoTriggerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request == rhs.request;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uavcontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f7e5ad6ab0ddf42c5727a195315a470";
  }

  static const char* value(const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f7e5ad6ab0ddf42ULL;
  static const uint64_t static_value2 = 0xc5727a195315a470ULL;
};

template<class ContainerAllocator>
struct DataType< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uavcontrol_msgs/arucoTriggerRequest";
  }

  static const char* value(const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool request \n"
;
  }

  static const char* value(const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arucoTriggerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uavcontrol_msgs::arucoTriggerRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAVCONTROL_MSGS_MESSAGE_ARUCOTRIGGERREQUEST_H
