// Generated by gencpp from file uavcontrol_msgs/GeoFence.msg
// DO NOT EDIT!


#ifndef UAVCONTROL_MSGS_MESSAGE_GEOFENCE_H
#define UAVCONTROL_MSGS_MESSAGE_GEOFENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uavcontrol_msgs
{
template <class ContainerAllocator>
struct GeoFence_
{
  typedef GeoFence_<ContainerAllocator> Type;

  GeoFence_()
    : x_min(0.0)
    , x_max(0.0)
    , y_min(0.0)
    , y_max(0.0)
    , z_min(0.0)
    , z_max(0.0)  {
    }
  GeoFence_(const ContainerAllocator& _alloc)
    : x_min(0.0)
    , x_max(0.0)
    , y_min(0.0)
    , y_max(0.0)
    , z_min(0.0)
    , z_max(0.0)  {
  (void)_alloc;
    }



   typedef double _x_min_type;
  _x_min_type x_min;

   typedef double _x_max_type;
  _x_max_type x_max;

   typedef double _y_min_type;
  _y_min_type y_min;

   typedef double _y_max_type;
  _y_max_type y_max;

   typedef double _z_min_type;
  _z_min_type z_min;

   typedef double _z_max_type;
  _z_max_type z_max;





  typedef boost::shared_ptr< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> const> ConstPtr;

}; // struct GeoFence_

typedef ::uavcontrol_msgs::GeoFence_<std::allocator<void> > GeoFence;

typedef boost::shared_ptr< ::uavcontrol_msgs::GeoFence > GeoFencePtr;
typedef boost::shared_ptr< ::uavcontrol_msgs::GeoFence const> GeoFenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uavcontrol_msgs::GeoFence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uavcontrol_msgs::GeoFence_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::GeoFence_<ContainerAllocator2> & rhs)
{
  return lhs.x_min == rhs.x_min &&
    lhs.x_max == rhs.x_max &&
    lhs.y_min == rhs.y_min &&
    lhs.y_max == rhs.y_max &&
    lhs.z_min == rhs.z_min &&
    lhs.z_max == rhs.z_max;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uavcontrol_msgs::GeoFence_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::GeoFence_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uavcontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad99bb284c3254d76796e1b66efe44bd";
  }

  static const char* value(const ::uavcontrol_msgs::GeoFence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad99bb284c3254d7ULL;
  static const uint64_t static_value2 = 0x6796e1b66efe44bdULL;
};

template<class ContainerAllocator>
struct DataType< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uavcontrol_msgs/GeoFence";
  }

  static const char* value(const ::uavcontrol_msgs::GeoFence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x_min\n"
"float64 x_max\n"
"float64 y_min\n"
"float64 y_max\n"
"float64 z_min\n"
"float64 z_max\n"
"\n"
;
  }

  static const char* value(const ::uavcontrol_msgs::GeoFence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x_min);
      stream.next(m.x_max);
      stream.next(m.y_min);
      stream.next(m.y_max);
      stream.next(m.z_min);
      stream.next(m.z_max);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeoFence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uavcontrol_msgs::GeoFence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uavcontrol_msgs::GeoFence_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "x_min: ";
    Printer<double>::stream(s, indent + "  ", v.x_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x_max: ";
    Printer<double>::stream(s, indent + "  ", v.x_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_min: ";
    Printer<double>::stream(s, indent + "  ", v.y_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y_max: ";
    Printer<double>::stream(s, indent + "  ", v.y_max);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_min: ";
    Printer<double>::stream(s, indent + "  ", v.z_min);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z_max: ";
    Printer<double>::stream(s, indent + "  ", v.z_max);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAVCONTROL_MSGS_MESSAGE_GEOFENCE_H
