// Generated by gencpp from file uavcontrol_msgs/LivoxCustomPoint.msg
// DO NOT EDIT!


#ifndef UAVCONTROL_MSGS_MESSAGE_LIVOXCUSTOMPOINT_H
#define UAVCONTROL_MSGS_MESSAGE_LIVOXCUSTOMPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uavcontrol_msgs
{
template <class ContainerAllocator>
struct LivoxCustomPoint_
{
  typedef LivoxCustomPoint_<ContainerAllocator> Type;

  LivoxCustomPoint_()
    : offset_time(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , reflectivity(0)
    , tag(0)
    , line(0)  {
    }
  LivoxCustomPoint_(const ContainerAllocator& _alloc)
    : offset_time(0)
    , x(0.0)
    , y(0.0)
    , z(0.0)
    , reflectivity(0)
    , tag(0)
    , line(0)  {
  (void)_alloc;
    }



   typedef uint32_t _offset_time_type;
  _offset_time_type offset_time;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef uint8_t _reflectivity_type;
  _reflectivity_type reflectivity;

   typedef uint8_t _tag_type;
  _tag_type tag;

   typedef uint8_t _line_type;
  _line_type line;





  typedef boost::shared_ptr< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> const> ConstPtr;

}; // struct LivoxCustomPoint_

typedef ::uavcontrol_msgs::LivoxCustomPoint_<std::allocator<void> > LivoxCustomPoint;

typedef boost::shared_ptr< ::uavcontrol_msgs::LivoxCustomPoint > LivoxCustomPointPtr;
typedef boost::shared_ptr< ::uavcontrol_msgs::LivoxCustomPoint const> LivoxCustomPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator2> & rhs)
{
  return lhs.offset_time == rhs.offset_time &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.reflectivity == rhs.reflectivity &&
    lhs.tag == rhs.tag &&
    lhs.line == rhs.line;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uavcontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "109a3cc548bb1f96626be89a5008bd6d";
  }

  static const char* value(const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x109a3cc548bb1f96ULL;
  static const uint64_t static_value2 = 0x626be89a5008bd6dULL;
};

template<class ContainerAllocator>
struct DataType< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uavcontrol_msgs/LivoxCustomPoint";
  }

  static const char* value(const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Livox costom pointcloud format.\n"
"\n"
"uint32 offset_time      # offset time relative to the base time\n"
"float32 x               # X axis, unit:m\n"
"float32 y               # Y axis, unit:m\n"
"float32 z               # Z axis, unit:m\n"
"uint8 reflectivity      # reflectivity, 0~255\n"
"uint8 tag               # livox tag\n"
"uint8 line              # laser number in lidar\n"
"\n"
;
  }

  static const char* value(const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.offset_time);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.reflectivity);
      stream.next(m.tag);
      stream.next(m.line);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LivoxCustomPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uavcontrol_msgs::LivoxCustomPoint_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "offset_time: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.offset_time);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "reflectivity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.reflectivity);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "tag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tag);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "line: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.line);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAVCONTROL_MSGS_MESSAGE_LIVOXCUSTOMPOINT_H
