// Generated by gencpp from file uavcontrol_msgs/ShoutStates.msg
// DO NOT EDIT!


#ifndef UAVCONTROL_MSGS_MESSAGE_SHOUTSTATES_H
#define UAVCONTROL_MSGS_MESSAGE_SHOUTSTATES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uavcontrol_msgs
{
template <class ContainerAllocator>
struct ShoutStates_
{
  typedef ShoutStates_<ContainerAllocator> Type;

  ShoutStates_()
    : is_active(false)
    , state()  {
    }
  ShoutStates_(const ContainerAllocator& _alloc)
    : is_active(false)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _is_active_type;
  _is_active_type is_active;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> const> ConstPtr;

}; // struct ShoutStates_

typedef ::uavcontrol_msgs::ShoutStates_<std::allocator<void> > ShoutStates;

typedef boost::shared_ptr< ::uavcontrol_msgs::ShoutStates > ShoutStatesPtr;
typedef boost::shared_ptr< ::uavcontrol_msgs::ShoutStates const> ShoutStatesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator2> & rhs)
{
  return lhs.is_active == rhs.is_active &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator1> & lhs, const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uavcontrol_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1165944cad65c58bd2d119eb4ad9c08c";
  }

  static const char* value(const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1165944cad65c58bULL;
  static const uint64_t static_value2 = 0xd2d119eb4ad9c08cULL;
};

template<class ContainerAllocator>
struct DataType< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uavcontrol_msgs/ShoutStates";
  }

  static const char* value(const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool is_active  # 喊话开关状态：true=开启，false=关闭\n"
"string state\n"
;
  }

  static const char* value(const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.is_active);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShoutStates_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uavcontrol_msgs::ShoutStates_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uavcontrol_msgs::ShoutStates_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "is_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_active);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAVCONTROL_MSGS_MESSAGE_SHOUTSTATES_H
