(cl:in-package uavcontrol_msgs-msg)
(cl:export '(ID-VAL
          ID
          DETECT-VAL
          DETECT
          OBJECTX-VAL
          OBJECTX
          OBJECTY-VAL
          OBJECTY
          OBJECTWIDTH-VAL
          OBJECTWIDTH
          OBJECTHEIGHT-VAL
          OBJECTHEIGHT
          FRAMEWIDTH-VAL
          FRAMEWIDTH
          FRAMEHEIGHT-VAL
          FRAMEHEIGHT
          KP-VAL
          KP
          KI-VAL
          KI
          KD-VAL
          KD
          CTLMODE-VAL
          CTLMODE
          CURRSIZE-VAL
          CURRSIZE
          MAXSIZE-VAL
          MAXSIZE
          MINSIZE-VAL
          MINSIZE
          TRACKIGNOREERROR-VAL
          TRACKIGNOREERROR
          AUTOZOOM-VAL
          AUTOZOOM
))